name: base
channels:
  - conda-forge
  - r
  - bioconda
dependencies:
  - r-essentials
  - r-devtools
  - r-openxlsx
  - r-plotROC
  - r-multcomp
  - r-pbkrtest
  - r-mvtnorm
  - r-SparseM
  - r-lme4
  - r-gbm
  - r-ranger
  - r-ROCR
  - r-multcomp
  - r-RColorBrewer
  - r-survival
  - r-ggpubr
  - r-survminer
  - r-gifski
  - r-ClassDiscovery
  - r-glmnet
  - r-pheatmap
  - r-ggfortify
  - r-lars
  - r-randomForest
  - r-clusterCrit
  - r-parallelDist=0.2.6
  - r-sampling
  - r-dbscan
  - r-rjson
  - r-circlize
  - r-GetoptLong
  - r-clue
  - r-GlobalOptions
  - r-ape
  - r-wgcna
  - r-Seurat
  - r-tsne
  - r-R2HTML
  - r-rbokeh
